version: "3"

services:
  app:
    image: ghcr.io/nevar-bot/nevar:main
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 8085:8085
      - 8075:8075
    environment:
      MONGO_HOST: db
      MONGO_PORT: 27017
      MONGO_USERNAME: nevar
      MONGO_PASSWORD: nevarpassword
      MONGO_DBNAME: nevar
    volumes:
      - ./config.toml:/app/config.toml
  db:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: nevar
      MONGO_INITDB_ROOT_PASSWORD: nevarpassword
    volumes:
      - db:/data/db

volumes:
  db: